app_admin:
    path: /listUsers
    controller: App\Controller\UserController::admin
add:
    path: /add
    controller: App\Controller\UserController::add
edit:
    path: /edit/{id}
    controller: App\Controller\UserController::edit
remove:
    path: /remove/{id}
    controller: App\Controller\UserController::remove

list_profile_front:
    path: /front/listeprofile
    controller: 'App\Controller\UserController::listuserFront'

search_skills:
    path: /search-skills
    controller: App\Controller\OfferController::searchSkills
    methods: GET
# Routes pour l'entretien
entretientf_index:
    path: /entretientf
    controller: 'App\Controller\EntretientfController::index'

entretientf_new:
    path: /entretientf/new
    controller: 'App\Controller\EntretientfController::new'

entretientf_show:
    path: /entretientf/{id}
    controller: 'App\Controller\EntretientfController::show'

entretientf_edit:
    path: /entretientf/{id}/edit
    controller: 'App\Controller\EntretientfController::edit'

entretientf_delete:
    path: /entretientf/{id}/delete
    controller: 'App\Controller\EntretientfController::delete'

# Routes pour l'entretien
entretient_index:
    path: /entretient
    controller: 'App\Controller\EntretientController::index'

entretient_new:
    path: /entretient/new
    controller: 'App\Controller\EntretientController::new'

entretient_show:
    path: /entretient/{id}
    controller: 'App\Controller\EntretientController::show'

entretient_edit:
    path: /entretient/{id}/edit
    controller: 'App\Controller\EntretientController::edit'

entretient_delete:
    path: /entretient/{id}/delete
    controller: 'App\Controller\EntretientController::delete'

# Routes pour RecrutementController
recrutement_index:
    path: /recrutement
    controller: 'App\Controller\RecrutementController::index'

recrutement_new:
    path: /recrutement/new
    controller: 'App\Controller\RecrutementController::new'

recrutement_show:
    path: /recrutement/{id}
    controller: 'App\Controller\RecrutementController::show'

recrutement_edit:
    path: /recrutement/{id}/edit
    controller: 'App\Controller\RecrutementController::edit'

recrutement_delete:
    path: /recrutement/{id}/delete
    controller: 'App\Controller\RecrutementController::delete'

# Routes pour RecrutementfController
recrutementf_index:
    path: /recrutementf
    controller: 'App\Controller\RecrutementfController::index'

recrutementf_new:
    path: /recrutementf/new
    controller: 'App\Controller\RecrutementfController::new'

recrutementf_show:
    path: /recrutementf/{id}
    controller: 'App\Controller\RecrutementfController::show'

recrutementf_edit:
    path: /recrutementf/{id}/edit
    controller: 'App\Controller\RecrutementfController::edit'

recrutementf_delete:
    path: /recrutementf/{id}/delete
    controller: 'App\Controller\RecrutementfController::delete'